level02.가장 큰 수 (미완)
DKU-STUDY/Algorithm pull request #401
Opened 2020-08-24 15:08 UTC by RockMiin

생각해보는데 왜 안되는지 모르겠네요
도움 주시면 감사하겠습니다

2020-08-25 03:34 UTC, JunilHwang requested changes
- 0 또는 양의 정수가 주어졌을 때, 정수를 이어 붙여 만들 수 있는 가장 큰 수를 알아내 주세요.
- numbers의 원소는 0 이상 1,000 이하입니다.

그런데 굳이 한 자리의 수 * 4를 할 필요가 있을까요?
사실 1~4 자리의 숫자가 올 수 있기 때문에
1자리 뿐만 아니라
2자리도, 3자리도 4자리 숫자로 만들어줘야할것같아요.

이보다 더 좋은 방법은

- 배열의 숫자를 문자로 바꾼다
- 내림차순 정렬을 한다.
- 이어붙인다.
- 원소에 0밖에 없으면 0을 반환한다.

이렇게 풀이할 수 있습니다!

2020-08-25 12:44 UTC, JeongShin commented
준일이형이 코멘트 해주신 방법대로 풀이 해봤는데 필요하시면 참고 하셔도 될꺼 같아요 ! 

https://github.com/DKU-STUDY/Algorithm/blob/master/programmers/%EB%82%9C%EC%9D%B4%EB%8F%84%EB%B3%84/level02.%EA%B0%80%EC%9E%A5_%ED%81%B0_%EC%88%98/JeongShin.js

2020-08-25 13:31 UTC, dkdlelk99 commented
인상깊었던 문제네요. a4 두장 정도를 테스트 케이스 생각해보면서 규칙을 찾다가 결국 솔루션을 보고 해결했었습니다.

혼자 해결하진 못했지만 솔루션을 봤을 때 파이썬이 `숫자로 이루어진 문자열`을 어떻게 정렬하는지가 인상 깊었어요.

이 문제에서는 `숫자로 이루어진 문자열을 어떻게 정렬하는지` 이게 핵심이었다고 생각해요.

* 파이썬에서 `print('12' < '11119')` 를 출력하면 결과는 `True`입니다.

간단하게 생각하자면 더 짧은 문자열의 길이만큼만 숫자의 크기를 비교하는듯 합니다.
~~왜그런지는 저도 잘..~~

그래서 각 숫자를 같은 길이만큼 맞춰줄 필요가 없습니다.
같은 룰을 적용하는게 나중에 더 쉽더라구요.

전부다 문자열로 만들고 3배로 늘려주면 알아서 sorting합니다.

정리하자면
1. 기존의 원소들의 자릿수를 생각할 필요가 없으므로 전부다 3배로 늘려도 상관 없다.  (파이썬의 `숫자로 이루어진 문자열` 소팅 방식)
2. 내림차순으로 정렬
3. 원소들의 원상 복귀
4. 리턴

2020-08-26 11:28 UTC, RockMiin commented
제가 생각을 조금 잘못 했던 것 같네요. 다들 도움 주셔서 풀 수 있었던 것같습니다. 매번 좋은 리뷰 감사합니다 !!

2020-08-26 11:28 UTC, merged