[Level03] 이중우선순위큐
DKU-STUDY/Algorithm pull request #940
Opened 2021-06-21 03:02 UTC by sangmandu

2021-06-21 12:47 UTC, JunilHwang requested changes
코드리뷰 테스트

2021-06-21 12:47 UTC, JunilHwang commented on programmers/난이도별/level03.이중우선순위큐/sangmandu.py
> +def solution(operations):
상민이 바보

2021-06-21 12:47 UTC, JunilHwang commented on programmers/난이도별/level03.이중우선순위큐/sangmandu.py
> +        else:
상민이 바보 2

2021-06-21 12:47 UTC, JunilHwang commented on programmers/난이도별/level03.이중우선순위큐/sangmandu.py
> +무슨 문제였는지 기억이 잘 안난다.
```suggestion
이렇게 바꿔보세요
```

2021-06-21 15:31 UTC, sangmandu commented
> 코드리뷰 테스트

아닛?? 바보?? ㅋ__ㅋ

2021-06-23 07:26 UTC, Go-yj commented on programmers/난이도별/level03.이중우선순위큐/sangmandu.py
> +                que = nlargest(len(que), que)[1:][::-1]
최댓값 찾는 방법 신박쓰
저 오늘 제출한 '문자열 내 맘대로 정렬하기'에서도 느꼈는데 인덱싱 잘 활용하시네요 😎

2021-06-25 03:50 UTC, merged